#cloud-config
hostname: ubuntu
users:
  - name: ubuntu
    # plain_text_passwd: ubuntu
    lock_passwd: false
    primary_group: ubuntu
    groups: sudo, wheel, adm, audio, cdrom, dialout, floppy, video, plugdev, dip, netdev
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
    - ${public_key}